name: news_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Internet
  dio: ^4.0.0
  # Value Equality
  equatable: ^2.0.3
  # State Management
  flutter_bloc: ^7.3.0
  # Dialog
  fluttertoast: ^8.0.8
  # Service locator
  get_it: ^7.1.3
  # Local Cache
  shared_preferences: ^2.0.6
  # Internet Checker
  internet_connection_checker: ^0.0.1+3
  # Dialog
  ndialog: ^4.1.0
  # Shimmer
  shimmer: ^2.0.0
  # Icon
  material_design_icons_flutter: ^5.0.6595
  # Webview
  webview_flutter: ^2.0.13
  # Change app package name
  change_app_package_name: ^1.0.0
  # Firebase
  firebase_core: ^1.10.6
  firebase_analytics: ^9.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Generate dart file
  build_runner: ^2.1.0
  # Unit test
  mockito: ^5.0.10

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/poppins/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
